export {
  EDIT_OVERLAY_FONT_FAMILY,
  EDIT_OVERLAY_FONT_WEIGHT,
  EDIT_OVERLAY_FFMPEG_SHADOW_COLOR,
  EDIT_OVERLAY_HORIZONTAL_INSET_PERCENT,
  EDIT_OVERLAY_MAX_TEXT_WIDTH_PERCENT,
  EDIT_OVERLAY_OUTPUT_DIMENSIONS,
  EDIT_OVERLAY_SHADOW_COLOR,
  EDIT_OVERLAY_SHADOW_OFFSET_PX,
  EDIT_OVERLAY_TEXT_COLOR,
  EDIT_OVERLAY_VERTICAL_INSET_PERCENT,
  getEditOverlayBackgroundColor,
  getEditOverlayBackgroundOpacity,
  getEditOverlayOutputDimensions,
  getEditOverlayPaddingForFontSize,
  getEditOverlayRenderMetrics,
  getEditOverlayTextShadow,
  type EditOverlayRatio,
  type EditOverlayStyle,
} from "@/worker/src/lib/edit-overlay-render-spec";
