/* eslint-disable @typescript-eslint/no-require-imports -- Isolated real-component browser regression. */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const http = require('node:http');
const path = require('node:path');
const { webpack } = require('next/dist/compiled/webpack/webpack');
let playwright;
try { playwright = require('playwright'); }
catch { playwright = require(path.join(process.env.USERPROFILE, '.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright')); }
const root = path.resolve(__dirname, '..'), out = path.join(root, '.tmp/explore-slideshow-browser');
fs.mkdirSync(out, { recursive: true });
const file = (name, content) => fs.writeFileSync(path.join(out, name), content);
file('loader.cjs', `const ts = require(${JSON.stringify(require.resolve('typescript'))}); module.exports = source => ts.transpileModule(source, {compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext,jsx:ts.JsxEmit.ReactJSX}}).outputText;`);
file('auth.ts', `import {createContext,useContext} from 'react'; export const AuthContext=createContext({user:{uid:'owner-a'}}); export const useAuth=()=>useContext(AuthContext); export async function getCurrentUserIdToken(owner) { if(owner && owner!==window.fixtureOwner) throw new Error('Your signed-in account changed.'); return 'fixture-'+window.fixtureOwner; }`);
file('media.ts', `export async function fetchAIStudioMediaAsset(id,token) { const response=await fetch('/fixture-media/'+id,{headers:{Authorization:'Bearer '+token}}); if(!response.ok)throw new Error('Unavailable fixture image');return response.json(); }
export async function fetchAIStudioMediaAssets({token}) { const response=await fetch('/fixture-media-list',{headers:{Authorization:'Bearer '+token}});return response.json(); }
export async function uploadAIStudioReferenceMedia(file,kind,limit,owner,options) { const response=await fetch('/fixture-upload?name='+encodeURIComponent(file.name)+'&purpose='+options.purpose,{headers:{Authorization:'Bearer fixture-'+owner}}); if(!response.ok)throw new Error('Fixture upload failed');return {kind,asset:await response.json()}; }
export const readAIStudioReferenceMetadata=async()=>({width:720,height:1280,ratio:'9:16'});`);
file('panel-ui.tsx', `export const AiStudioComposer=props=><div><textarea aria-label='Selection fixture prompt' value={props.prompt} onChange={event=>props.onPromptChange(event.target.value)}/><button disabled={props.generateDisabled} onClick={props.onSubmit}>Generate selection fixture</button>{props.settings}</div>;export const AiStudioSettingSelect=()=>null;export const AiStudioRatioPicker=()=>null;export const AiStudioResults=props=><div>{props.children}</div>;export const AiStudioResultActions=()=>null;export const ImageGenerationHistory=()=>null;export const ReferenceMediaUpload=()=>null;`);
file('jobs.ts', `export const persistJobIdInUrl=()=>{};export const useStoredBackgroundJobIds=()=>[];export const useRecoverableWorkflowJobs=()=>({queries:[],recovering:false,recoveryError:null});export const useCancelBackgroundJob=()=>({isPending:false});export const usePersistedJobIdFromUrl=()=>null;export const useRetryBackgroundJob=()=>({isPending:false});`);
file('ui.tsx', `import {createContext,useContext} from 'react'; export const Button=({variant,size,...props})=><button {...props}/>;
const Context=createContext(null); export const Popover=({open,onOpenChange,children})=><Context.Provider value={{open,onOpenChange}}>{children}</Context.Provider>;
export const PopoverTrigger=({render,children,...props})=>{const context=useContext(Context);return <button {...render.props} {...props} onClick={()=>context.onOpenChange(!context.open)}>{children}</button>;};
export const PopoverContent=({side,align,children,...props})=>useContext(Context).open?<div role='dialog' {...props}>{children}</div>:null; export const PopoverTitle=props=><h2 {...props}/>;`);
file('entry.tsx', `import {createRoot} from 'react-dom/client'; import {useState,useRef,useCallback} from 'react'; import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {AuthContext} from './auth'; import {FormatSlideshowEditor} from '@/components/explore/format-slideshow-editor'; import {FormatInstructionImageReference} from '@/components/explore/format-instruction-image-reference';import {ImageGenerationStudioPanel} from '@/components/workspace/ugc-chat-workspace';
const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0'), image=n=>({id:id(n),url:'https://owned.test/'+n+'.png',title:'Owned image '+n,createdAt:'2026-10-09T00:00:00Z',aspectRatio:'4:5'});
const guide={id:'catalogue-twelve',format:'slideshow',title:'Layout guide',slides:Array.from({length:12},(_,i)=>({id:'guide-'+i,url:'https://owned.test/guide-'+i+'.png'}))}, legacyGuide={...guide,id:'legacy-guide',slides:guide.slides.slice(0,2)}, legacyReferences=[legacyGuide];
window.fixtureOwner=sessionStorage.getItem('fixtureOwner')??'owner-a';
function Fixture(){const [owner,setOwner]=useState(window.fixtureOwner);window.changeOwner=next=>{window.fixtureOwner=next;sessionStorage.setItem('fixtureOwner',next);setOwner(next);}; return <AuthContext.Provider value={{user:{uid:owner}}}><Owned key={owner} owner={owner}/></AuthContext.Provider>;}
function Owned({owner}) {const controller=useRef(null),[controls,sc]=useState(null),[results,sr]=useState(null),[actions,sa]=useState(null),[output,so]=useState(null),[busy,sb]=useState(false),[generating,sg]=useState(false),[recreate,setRecreate]=useState(null),[selection,ss]=useState(null),[pending,sp]=useState(false),[error,se]=useState(null),[active,setActive]=useState(true),[reference,setReference]=useState(guide);
const saved=useCallback(so,[]),dirty=useCallback(()=>so(null),[]),report=useCallback(sb,[]);
return <><p data-testid='owner'>{owner}</p><button onClick={()=>controller.current.useImage(image(1))}>Add generated 1</button><button onClick={()=>controller.current.useImage(image(2))}>Add generated 2</button><button onClick={()=>controller.current.useImage(image(3))}>Use generated 3</button><button onClick={()=>sg(value=>!value)}>Toggle generating</button><button onClick={()=>setReference(legacyGuide)}>Choose legacy guide</button><p data-testid='busy'>{String(busy)}</p><p data-testid='target'>{recreate??''}</p><p data-testid='output'>{output?.id??''}</p><div ref={sc}/><div ref={sr}/><div ref={sa}/>
<FormatSlideshowEditor reference={reference} legacyReferences={legacyReferences} controllerRef={controller} active generationBusy={generating} controlsTarget={controls} resultsTarget={results} actionsTarget={actions} localPreview={false} savingEnabled onDirty={dirty} onSaved={saved} onContinue={()=>{}} onRegenerate={index=>setRecreate(index)} onBusyChange={report}/>
<div style={{position:'relative',height:100}}><FormatInstructionImageReference key={owner} ownerId={owner} selection={selection} onChange={ss} onPendingChange={sp} onErrorChange={se} disabled={false} active={active}/></div><button onClick={()=>setActive(value=>!value)}>Toggle attachment active</button><button disabled={pending||!!error}>Generate fixture</button><p data-testid='attachment'>{selection?.asset.id??''}</p></>;}
function SelectionFixture(){const controller=useRef(null),[busy,sb]=useState(false),[controls,sc]=useState(null),[results,sr]=useState(null),[actions,sa]=useState(null),[selected,ss]=useState('');const noop=useCallback(()=>{},[]),report=useCallback(sb,[]);return <AuthContext.Provider value={{user:{uid:'owner-a'},loading:false}}><p data-testid='selection-busy'>{String(busy)}</p><p data-testid='selected-image'>{selected}</p><button onClick={()=>{controller.current.useImage(image(1));controller.current.useImage(image(2));}}>Seed selection slides</button><div ref={sc}/><div ref={sr}/><div ref={sa}/><FormatSlideshowEditor reference={guide} legacyReferences={legacyReferences} controllerRef={controller} active generationBusy={busy} controlsTarget={controls} resultsTarget={results} actionsTarget={actions} localPreview={false} savingEnabled onDirty={noop} onSaved={noop} onContinue={noop} onRegenerate={noop}/><ImageGenerationStudioPanel accessState='pro' recreateView={{referenceImageUrl:guide.slides[0].url,workflow:{format:'slideshow',onBusyChange:report,onGenerationStart:noop,onSelectImage:image=>{ss(image.id);controller.current.useImage(image);}}}}/></AuthContext.Provider>;}
const root=createRoot(document.getElementById('root')),queryClient=new QueryClient({defaultOptions:{queries:{retry:false}}});root.render(<QueryClientProvider client={queryClient}><Fixture/></QueryClientProvider>);window.renderSelectionFixture=()=>{window.fixtureOwner='owner-a';root.render(<QueryClientProvider client={queryClient}><SelectionFixture/></QueryClientProvider>);};`);

const id = n => `00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const asset = n => ({id:id(n),title:`Owned image ${n}`,collection:'image',status:'ready',sourceType:'upload',createdAt:'2026-10-09T00:00:00Z',updatedAt:'2026-10-09T00:00:00Z',mimeType:'image/png',fileName:`image-${n}.png`,fileSizeBytes:128,durationSeconds:null,width:1080,height:1350,ratio:'4:5',projectId:'explore-slides',sourceRecordId:null,parentAssetId:null,thumbnailUrl:null,metadata:{},url:`https://owned.test/${n}.png`});
const saves = [], stored = new Map(); let failAcknowledgement = false, rejectRetry = false, slowSelectionLookup = false, uploadCount = 10;
const json = (response, value, status = 200) => {response.statusCode=status;response.setHeader('Content-Type','application/json');response.end(JSON.stringify(value));};
async function main() {
  const aliases={'@/contexts/auth-context':path.join(out,'auth.ts'),'@/lib/firebase/auth':path.join(out,'auth.ts'),'@/lib/ai-studio/media-client':path.join(out,'media.ts'),'@/lib/ai-studio/reference-media-upload':path.join(out,'media.ts'),'@/components/ui/button':path.join(out,'ui.tsx'),'@/components/ui/popover':path.join(out,'ui.tsx'),'@/lib/jobs/background-job-client':path.join(out,'jobs.ts'),'@/components/generation/ai-studio-composer':path.join(out,'panel-ui.tsx'),'@/components/generation/ai-studio-results':path.join(out,'panel-ui.tsx'),'@/components/generation/ai-studio-result-actions':path.join(out,'panel-ui.tsx'),'@/components/generation/image-generation-history':path.join(out,'panel-ui.tsx'),'@/components/generation/reference-media-upload':path.join(out,'panel-ui.tsx'),'@':root};
  await new Promise((resolve,reject)=>{const compiler=webpack({mode:'development',devtool:false,context:root,entry:path.join(out,'entry.tsx'),output:{path:out,filename:'bundle.js'},resolve:{extensions:['.tsx','.ts','.js'],alias:aliases},module:{rules:[{test:/\.tsx?$/,use:path.join(out,'loader.cjs')}]}});compiler.run((error,stats)=>compiler.close(()=>error||stats.hasErrors()?reject(error||new Error(stats.toString({all:false,errors:true}))):resolve()));});
  const server=http.createServer(async(request,response)=>{
    const url=new URL(request.url,'http://fixture');
    if(url.pathname==='/fixture'){response.setHeader('Content-Type','text/html');return response.end('<div id="root"></div><script>window.process={env:{}}</script><script src="/bundle.js"></script>');}
    if(url.pathname==='/bundle.js'){response.setHeader('Content-Type','text/javascript');return response.end(fs.readFileSync(path.join(out,'bundle.js')));}
    assert.ok(request.headers.authorization?.startsWith('Bearer fixture-owner-'));
    if(url.pathname.startsWith('/fixture-media/')){const number=Number(url.pathname.split('/').at(-1).split('-').at(-1));if(slowSelectionLookup)await new Promise(resolve=>setTimeout(resolve,900));return number===99?json(response,{error:'Unavailable owned image'},404):json(response,{...asset(number),sourceType:'generated_image'});}
    if(url.pathname.startsWith('/api/media/')){const number=Number(url.pathname.split('/').at(-1).split('-').at(-1));if(slowSelectionLookup)await new Promise(resolve=>setTimeout(resolve,900));return json(response,{ok:true,asset:{...asset(number),sourceType:'generated_image'}});}
    if(url.pathname==='/fixture-media-list')return json(response,[1,2,3].map(n=>({...asset(n),sourceType:'generated_image',createdAt:new Date().toISOString(),metadata:{exploreFormat:'slideshow'}})));
    if(url.pathname==='/fixture-upload'){
      assert.ok(['explore-reference','explore-slides'].includes(url.searchParams.get('purpose')));
      if(url.searchParams.get('name').startsWith('slow'))await new Promise(resolve=>setTimeout(resolve,900));
      return json(response,asset(++uploadCount));
    }
    if(url.pathname==='/api/media')return json(response,{ok:true,assets:[]});
    if(url.pathname==='/api/library')return json(response,{ok:true,items:[...stored].map(([key,value])=>({id:value.id,title:value.title,sourceId:'explore-slideshow:'+key,projectId:'explore',slideCount:value.slides.length,slides:value.slides.map((renderedUrl,index)=>({slideNumber:index+1,renderedUrl}))}))});
    if(url.pathname==='/api/explore/slideshows'){
      let raw='';for await(const chunk of request)raw+=chunk;const body=JSON.parse(raw);saves.push(body);assert.equal(body.requestKey,request.headers['idempotency-key']);if(body.version===2)assert.ok(body.slides.every(slide=>slide.mediaAssetId));
      if(rejectRetry){rejectRetry=false;return json(response,{ok:false,outcome:'rejected',error:'Unavailable retry'},503);}
      const slides=body.slides.map((slide,index)=>slide.mediaAssetId?asset(Number(slide.mediaAssetId.split('-').at(-1))).url:'https://owned.test/guide-'+index+'.png');
      const output={id:id(90+stored.size),kind:'library_item',title:'My slideshow',url:slides[0],slides};if(!stored.has(body.requestKey))stored.set(body.requestKey,output);
      await new Promise(resolve=>setTimeout(resolve,300));
      if(failAcknowledgement){failAcknowledgement=false;return json(response,{ok:false,error:'Lost fixture acknowledgement'},503);}
      return json(response,{ok:true,...stored.get(body.requestKey)});
    }
    throw new Error('Unexpected fixture request '+url.pathname);
  });
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  const browser=await playwright.chromium.launch({headless:true,...(process.platform==='win32'?{channel:'msedge'}:{})}),context=await browser.newContext(),page=await context.newPage();
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.route('https://owned.test/**',route=>route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j3ioAAAAASUVORK5CYII=','base64')}));
  const count=page.getByText('0 / 10',{exact:true}),save=()=>page.getByRole('button',{name:'Save slideshow',exact:true});
  try {
    await page.goto(`http://127.0.0.1:${server.address().port}/fixture`);await count.waitFor();await page.waitForFunction(()=>document.querySelector('[data-testid="busy"]').textContent==='false');assert.equal(await save().isDisabled(),true);
    await page.getByRole('button',{name:'Add generated 1',exact:true}).click();await page.getByRole('button',{name:'Add generated 2',exact:true}).click();await page.getByText('2 / 10',{exact:true}).waitFor();
    await page.getByRole('button',{name:'Move slide 2 earlier',exact:true}).click();await page.getByRole('button',{name:'Recreate slide 1',exact:true}).click();assert.equal(await page.getByTestId('target').textContent(),'0');
    await page.getByRole('button',{name:'Use generated 3',exact:true}).click();assert.equal(await page.getByText('2 / 10',{exact:true}).isVisible(),true);
    failAcknowledgement=true;await save().dblclick();await page.getByRole('button',{name:'Resume save',exact:true}).waitFor();assert.equal(saves.length,1);assert.deepEqual(saves[0].slides.map(slide=>slide.mediaAssetId),[id(3),id(1)]);
    assert.equal(await page.getByRole('button',{name:'Remove slide',exact:true}).isDisabled(),true);assert.equal(await page.getByTestId('output').textContent(),'');
    // A newer local draft must never masquerade as this unfinished save.
    await page.evaluate(()=>{const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');localStorage.setItem('ugc-explore:slideshow-draft:v2:owner-a',JSON.stringify({version:2,owner:'owner-a',slides:[{referenceSlideId:'different-1',mediaAssetId:id(7)},{referenceSlideId:'different-2',mediaAssetId:id(8)}]}));});
    await page.reload();await page.getByRole('button',{name:'Resume save',exact:true}).waitFor();assert.match(await page.getByAltText('Slide 1 of 2',{exact:true}).getAttribute('src'),/3\.png$/);
    rejectRetry=true;await page.getByRole('button',{name:'Resume save',exact:true}).click();await page.getByText('Unavailable retry',{exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Resume save',exact:true}).isEnabled(),true);
    assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('ugc-explore:slideshow-draft:v2:owner-a:save')).requestKey),saves[0].requestKey);
    await page.getByRole('button',{name:'Resume save',exact:true}).click();await page.getByRole('button',{name:'Continue to Schedule',exact:true}).waitFor();assert.equal(saves.length,3);assert.deepEqual(saves[2],saves[0]);assert.equal(stored.size,1);
    await page.reload();await page.getByRole('button',{name:'Continue to Schedule',exact:true}).waitFor();assert.equal(saves.length,3);
    await page.getByRole('button',{name:'Move slide 1 later',exact:true}).click();assert.equal(await page.getByTestId('output').textContent(),'');
    await page.getByRole('button',{name:'Toggle generating',exact:true}).click();assert.equal(await save().isDisabled(),true);await page.getByRole('button',{name:'Toggle generating',exact:true}).click();
    await page.getByLabel('Upload slideshow images',{exact:true}).setInputFiles([{name:'final.png',mimeType:'image/png',buffer:Buffer.from('fixture')}]);await page.getByText('3 / 10',{exact:true}).waitFor();
    failAcknowledgement=true;await save().click();await page.getByRole('button',{name:'Resume save',exact:true}).waitFor();
    const other=await page.context().newPage();await other.route('https://owned.test/**',route=>route.fulfill({contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j3ioAAAAASUVORK5CYII=','base64')}));
    await other.goto(page.url());await other.getByRole('button',{name:'Resume save',exact:true}).click();await other.getByRole('button',{name:'Continue to Schedule',exact:true}).waitFor();await other.close();
    const completedPosts=saves.length;await page.getByRole('button',{name:'Resume save',exact:true}).click();await page.getByRole('button',{name:'Continue to Schedule',exact:true}).waitFor();assert.equal(saves.length,completedPosts);assert.equal(await page.getByRole('button',{name:'Remove slide',exact:true}).isEnabled(),true);
    console.log('PASS actual slideshow editor: empty catalogue, add, replace, reorder, upload, single save, pending lock, stale draft recovery, exact retry, verified reload, generation lock');
    const attach=page.getByLabel('Choose instruction reference image',{exact:true});await attach.setInputFiles([{name:'slow-product.png',mimeType:'image/png',buffer:Buffer.from('fixture')}]);assert.equal(await page.getByRole('button',{name:'Generate fixture',exact:true}).isDisabled(),true);await page.getByAltText('Attached reference',{exact:true}).waitFor();
    const selected=await page.getByTestId('attachment').textContent();await attach.setInputFiles([{name:'bad.gif',mimeType:'image/gif',buffer:Buffer.from('bad')}]);await page.getByRole('button',{name:'Dismiss image upload error',exact:true}).waitFor();assert.equal(await page.getByTestId('attachment').textContent(),selected);await page.getByRole('button',{name:'Dismiss image upload error',exact:true}).click();assert.equal(await page.getByTestId('attachment').textContent(),selected);assert.equal(await page.getByRole('button',{name:'Generate fixture',exact:true}).isEnabled(),true);
    await page.getByRole('button',{name:'Add image to your instructions',exact:true}).click();await page.getByRole('dialog').waitFor();await page.getByRole('button',{name:'Toggle attachment active',exact:true}).evaluate(button=>button.click());assert.equal(await page.getByRole('dialog').count(),0);await page.getByRole('button',{name:'Toggle attachment active',exact:true}).evaluate(button=>button.click());assert.equal(await page.getByTestId('attachment').textContent(),selected);
    await attach.setInputFiles([{name:'slow-owner-change.png',mimeType:'image/png',buffer:Buffer.from('fixture')}]);await page.evaluate(()=>window.changeOwner('owner-b'));await page.waitForTimeout(1100);assert.equal(await page.getByTestId('attachment').textContent(),'');await page.getByText('0 / 10',{exact:true}).waitFor();assert.equal(await page.getByTestId('output').textContent(),'');
    await page.evaluate(()=>{const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');localStorage.setItem('ugc-explore:slideshow-draft:v2:owner-c:save',JSON.stringify({version:1,owner:'owner-c',requestKey:id(77),referenceId:'legacy-guide',slides:[{referenceSlideId:'guide-0',mediaAssetId:null},{referenceSlideId:'guide-1',mediaAssetId:id(2)}]}));window.changeOwner('owner-c');});
    await page.getByRole('button',{name:'Resume save',exact:true}).waitFor();assert.match(await page.getByAltText('Slide 1 of 2',{exact:true}).getAttribute('src'),/guide-0\.png$/);
    await page.reload();await page.getByRole('button',{name:'Resume save',exact:true}).waitFor();assert.match(await page.getByAltText('Slide 1 of 2',{exact:true}).getAttribute('src'),/guide-0\.png$/);await page.getByRole('button',{name:'Next',exact:true}).click();assert.match(await page.getByAltText('Slide 2 of 2',{exact:true}).getAttribute('src'),/2\.png$/);
    await page.getByRole('button',{name:'Resume save',exact:true}).click();await page.getByRole('button',{name:'Continue to Schedule',exact:true}).waitFor();await page.reload();await page.getByRole('button',{name:'Continue to Schedule',exact:true}).waitFor();assert.match(await page.getByAltText('Slide 1 of 2',{exact:true}).getAttribute('src'),/guide-0\.png$/);
    // A completed legacy receipt must not override subsequent owned drafts.
    await page.getByRole('button',{name:'Add generated 1',exact:true}).click();await page.getByRole('button',{name:'Add generated 2',exact:true}).click();await page.reload();await page.getByText('2 / 10',{exact:true}).waitFor();assert.equal(await page.getByTestId('output').textContent(),'');assert.match(await page.getByAltText('Slide 1 of 2',{exact:true}).getAttribute('src'),/1\.png$/);
    // This is a fresh UUID even though a completed legacy receipt preceded it.
    rejectRetry=true;await save().click();await page.getByText('Unavailable retry',{exact:true}).waitFor();assert.equal(await save().isEnabled(),true);assert.equal(await page.getByRole('button',{name:'Remove slide',exact:true}).isEnabled(),true);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('ugc-explore:slideshow-draft:v2:owner-c:save')).requestKey),id(77));
    await page.getByRole('button',{name:'Remove slide',exact:true}).click();await page.getByRole('button',{name:'Remove slide',exact:true}).click();await page.reload();await page.getByText('0 / 10',{exact:true}).waitFor();assert.equal(await page.getByTestId('output').textContent(),'');assert.equal(await page.getByAltText('Slide 1 of 2',{exact:true}).count(),0);
    // Initial v1 discovery must not replace missing owned footage with a guide.
    await page.evaluate(()=>{const id=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');localStorage.setItem('ugc-explore:slideshow-draft:v1:owner-d:legacy-guide:save',JSON.stringify({version:1,owner:'owner-d',requestKey:id(78),referenceId:'legacy-guide',slides:[{referenceSlideId:'guide-0',mediaAssetId:null},{referenceSlideId:'guide-1',mediaAssetId:id(99)}]}));window.changeOwner('owner-d');});await page.getByRole('button',{name:'Choose legacy guide',exact:true}).click();await page.getByRole('button',{name:'Resume save',exact:true}).waitFor();await page.getByRole('button',{name:'Next',exact:true}).click();await page.getByText('This image is unavailable. Replace it or remove this slide.',{exact:true}).waitFor();assert.equal(await page.getByAltText('Slide 2 of 2',{exact:true}).count(),0);
    console.log('PASS two-tab completion unlocks editing without a new POST; legacy mixed originals/owned images retain exact preview and request across reloads');
    console.log('PASS attachment: upload blocks generation, failed replacement preserves prior choice, dismissal retains image, navigation closes picker, account change ignores stale upload');
    await page.evaluate(()=>{localStorage.removeItem('ugc-explore:slideshow-draft:v2:owner-a');localStorage.removeItem('ugc-explore:slideshow-draft:v2:owner-a:save');window.renderSelectionFixture();});await page.getByRole('button',{name:'Seed selection slides',exact:true}).waitFor();await page.getByText('0 / 10',{exact:true}).waitFor();await page.waitForFunction(()=>document.querySelector('[data-testid="selection-busy"]').textContent==='false');await page.getByRole('button',{name:'Seed selection slides',exact:true}).click();await page.getByText('2 / 10',{exact:true}).waitFor();await page.getByRole('button',{name:'Preview slide 1',exact:true}).click();await page.getByRole('button',{name:'Recreate slide 1',exact:true}).click();await page.getByLabel('Selection fixture prompt',{exact:true}).fill('Keep the layout and update the subject');
    slowSelectionLookup=true;await page.locator('#ai-studio-image-result-'+id(3)).getByRole('button',{name:'Use this image',exact:true}).click();await page.waitForFunction(()=>document.querySelector('[data-testid="selection-busy"]').textContent==='true');assert.equal(await page.getByRole('button',{name:'Generate selection fixture',exact:true}).isDisabled(),true);assert.equal(await page.locator('#ai-studio-image-result-'+id(2)).getByRole('button',{name:'Use this image',exact:true}).isDisabled(),true);await page.getByRole('button',{name:'Preview slide 2',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Recreate slide 2',exact:true}).isDisabled(),true);
    await page.waitForFunction(id=>document.querySelector('[data-testid="selected-image"]').textContent===id,id(3));await page.waitForFunction(()=>document.querySelector('[data-testid="selection-busy"]').textContent==='false');assert.equal(await page.getByText('2 / 10',{exact:true}).isVisible(),true);assert.match(await page.getByAltText('Slide 1 of 2',{exact:true}).getAttribute('src'),/3\.png$/);assert.equal(await page.getByRole('button',{name:'Generate selection fixture',exact:true}).isEnabled(),true);console.log('PASS actual image panel: owned lookup locks generation, other selection and recreate target; correct original target replaced after lookup');
    assert.deepEqual(errors,[]);await page.screenshot({path:path.join(out,'verified.png')});
  } catch (error) { console.error(await page.locator('#root').innerText(),errors);await page.screenshot({path:path.join(out,'failure.png')});throw error; }
  finally {await browser.close();await new Promise(resolve=>server.close(resolve));}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
